import "./globals.css";
import Navigation from "../components/navigation";
import Footer from "../components/footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dutch Flags [dot] Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container mx-auto px-28 my-5 bg-silver">
        <div className="flex flex-col bg-beige min-h-screen px-20 py-8 last:items-end">
          <Navigation />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
