import "./globals.css";
import type { Metadata } from "next";
import Navigation from "../components/navigation";
import Footer from "../components/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container mx-auto px-28 my-5 bg-silver">
        <div className="bg-beige min-h-screen px-20 py-8">
          <Navigation />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
